"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";

import "./styles/css/styles.css";
import Navigation from "./components/navigation";
import Cart from "./components/cart";
import { GlobalContextProvider } from "./context/store";
import Footer from "./components/footer";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <GlobalContextProvider>
          <Navigation />
          <Cart />
          {children}
        </GlobalContextProvider>
        <Footer />
      </body>
    </html>
  );
}
